stasher:
  address: "127.0.0.1"
  port: "8080"
  salt: "longAndSecureSalt"
  hostname: "127.0.0.1:8080"
couchdb:
  protocol: "https"
  address: "localhost"
  port: "6984"
  dbname: "stasher"
  username: "stasher"
  password: "stasher"
  cert_check: false
